// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Data
{
    // Regio
    public class Regio
    {
        public int Regid { get; set; } // regid (Primary key)
        public string Regname { get; set; } // regname (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Countries where [Country].[ctyregid] point to this entity (FK_Country_Country)
        /// </summary>
        public virtual ICollection<Country> Countries { get; set; } // Country.FK_Country_Country

        public Regio()
        {
            Countries = new List<Country>();
        }
    }

}
// </auto-generated>
