// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Data
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class SelectAllCountriesBckReturnModel
    {
        public string ctyid { get; set; }
        public string ctyname { get; set; }
        public int ctyregid { get; set; }
    }

}
// </auto-generated>
