// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Data
{
    public class SelectAllRegioReturnModel
    {
        public int regid { get; set; }
        public string regname { get; set; }
    }

}
// </auto-generated>
