// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Data
{
    public class SelectCountryNameContainsReturnModel
    {
        public string ctyid { get; set; }
        public string ctyname { get; set; }
        public string regname { get; set; }
    }

}
// </auto-generated>
