// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace Data
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface IMyDbContext : IDisposable
    {
        DbSet<Country> Countries { get; set; } // Country
        DbSet<Regio> Regios { get; set; } // Regio

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);

        // Stored Procedures
        int CreateCountry(string ctyid, string ctyname, int? ctyregid);
        // CreateCountryAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int CreateRegio(int? regid, string regname);
        // CreateRegioAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int DeleteCountry(string ctyid);
        // DeleteCountryAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int DeleteRegio(int? regid);
        // DeleteRegioAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        List<SelectAllCountriesReturnModel> SelectAllCountries();
        List<SelectAllCountriesReturnModel> SelectAllCountries(out int procResult);
        Task<List<SelectAllCountriesReturnModel>> SelectAllCountriesAsync();

        List<SelectAllCountriesBckReturnModel> SelectAllCountriesBck();
        List<SelectAllCountriesBckReturnModel> SelectAllCountriesBck(out int procResult);
        Task<List<SelectAllCountriesBckReturnModel>> SelectAllCountriesBckAsync();

        List<SelectAllRegioReturnModel> SelectAllRegio();
        List<SelectAllRegioReturnModel> SelectAllRegio(out int procResult);
        Task<List<SelectAllRegioReturnModel>> SelectAllRegioAsync();

        List<SelectCountriesWithRegionNameReturnModel> SelectCountriesWithRegionName();
        List<SelectCountriesWithRegionNameReturnModel> SelectCountriesWithRegionName(out int procResult);
        Task<List<SelectCountriesWithRegionNameReturnModel>> SelectCountriesWithRegionNameAsync();

        List<SelectCountryReturnModel> SelectCountry(string countryId);
        List<SelectCountryReturnModel> SelectCountry(string countryId, out int procResult);
        Task<List<SelectCountryReturnModel>> SelectCountryAsync(string countryId);

        List<SelectCountryNameContainsReturnModel> SelectCountryNameContains(string ctyname);
        List<SelectCountryNameContainsReturnModel> SelectCountryNameContains(string ctyname, out int procResult);
        Task<List<SelectCountryNameContainsReturnModel>> SelectCountryNameContainsAsync(string ctyname);

    }
}
// </auto-generated>
