// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Data
{
    // Regio
    public class RegioConfiguration : IEntityTypeConfiguration<Regio>
    {
        public void Configure(EntityTypeBuilder<Regio> builder)
        {
            builder.ToTable("Regio", "dbo");
            builder.HasKey(x => x.Regid).HasName("PK_Regio").IsClustered();

            builder.Property(x => x.Regid).HasColumnName(@"regid").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Regname).HasColumnName(@"regname").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);

            // builder.HasIndex(x => x.Regname).HasDatabaseName("IX_Regio").IsUnique();
        }
    }

}
// </auto-generated>
